apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediasoup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediasoup
  template:
    metadata:
      labels:
        app: mediasoup
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: mediasoup
          image: odyssey-task-2-mediasoup:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: odyssey-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
